name: Build 3 APKs

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Install Dependencies
        run: |
          npm install
          chmod +x android/gradlew

      - name: Build User APK
        run: |
          cp cap.user.json capacitor.config.json
          cp assets/user.jpg assets/icon.png
          npx capacitor-assets generate --android
          npx cap sync android
          cd android && ./gradlew assembleRelease
          mv app/build/outputs/apk/release/app-release-unsigned.apk ../BattlePro-User.apk

      - name: Build Staff APK
        run: |
          cp cap.staff.json capacitor.config.json
          cp assets/staff.png assets/icon.png
          npx capacitor-assets generate --android
          npx cap sync android
          cd android && ./gradlew assembleRelease
          mv app/build/outputs/apk/release/app-release-unsigned.apk ../BattlePro-Staff.apk

      - name: Build Admin APK
        run: |
          cp cap.admin.json capacitor.config.json
          cp assets/admin.png assets/icon.png
          npx capacitor-assets generate --android
          npx cap sync android
          cd android && ./gradlew assembleRelease
          mv app/build/outputs/apk/release/app-release-unsigned.apk ../BattlePro-Admin.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: BattlePro-APKs
          path: ./*.apk
